/* =========================================================
   클래스 더미 데이터
   - 클래스 이미지는 sub1_1 ~ sub1_5 사용
       sub1_1 화과자        → 베이킹
       sub1_2 단팥크림빵    → 베이킹
       sub1_3 천연석 주얼리 → 주얼리
       sub1_4 칠보 키링     → 금속공예
       sub1_5 원목 볼펜     → 우드공예
   - 지역/가격/요일/거리를 다양하게 설정해 필터 동작 확인용
   - distance 는 미터(m) 단위, markerX/markerY 는 지도 위 퍼센트(%) 좌표
   ========================================================= */
const classData = [
  {
    id: 1,
    title: '플라워 화과자 원데이 클래스',
    category: '베이킹',
    region: '성수동',
    studio: '성수 화과자공방',
    schedule: '오늘 (화) 14:00 ~ 17:00',
    availableDays: ['화', '토'],
    timeSlot: '오후',
    classFormat: '소규모',
    reservationOptions: ['당일 예약 가능'],
    transportType: '도보',
    transportTime: 8,
    distance: 620,
    price: 48000,
    popularity: 92,
    createdAt: '2026-06-15',
    image: 'images/sub1_1.png',
    lat: 37.5445, lng: 127.056,
    markerX: 45, markerY: 32,
    isFavorite: false
  },
  {
    id: 2,
    title: '말차 화과자 티 클래스',
    category: '베이킹',
    region: '서울숲',
    studio: '서울숲 티하우스',
    schedule: '내일 (수) 11:00 ~ 13:30',
    availableDays: ['수', '금'],
    timeSlot: '오전',
    classFormat: '1:1 클래스',
    reservationOptions: ['이번 주 예약 가능'],
    transportType: '도보',
    transportTime: 10,
    distance: 800,
    price: 52000,
    popularity: 80,
    createdAt: '2026-06-12',
    image: 'images/sub1_1.png',
    lat: 37.5446, lng: 127.039,
    markerX: 30, markerY: 50,
    isFavorite: false
  },
  {
    id: 3,
    title: '앙버터 단팥크림빵 클래스',
    category: '베이킹',
    region: '성수동',
    studio: '성수 베이킹스튜디오',
    schedule: '내일 (수) 09:00 ~ 12:00',
    availableDays: ['수', '금', '토'],
    timeSlot: '오전',
    classFormat: '소규모',
    reservationOptions: ['이번 주 예약 가능'],
    transportType: '도보',
    transportTime: 6,
    distance: 480,
    price: 38000,
    popularity: 78,
    createdAt: '2026-06-10',
    image: 'images/sub1_2.png',
    lat: 37.5447, lng: 127.058,
    markerX: 52, markerY: 44,
    isFavorite: false
  },
  {
    id: 4,
    title: '촉촉 단팥빵 베이킹 클래스',
    category: '베이킹',
    region: '왕십리',
    studio: '왕십리 브레드랩',
    schedule: '모레 (목) 14:00 ~ 16:30',
    availableDays: ['목', '금'],
    timeSlot: '오후',
    classFormat: '단체 가능',
    reservationOptions: [],
    transportType: '도보',
    transportTime: 12,
    distance: 950,
    price: 35000,
    popularity: 70,
    createdAt: '2026-05-28',
    image: 'images/sub1_2.png',
    lat: 37.5613, lng: 127.037,
    markerX: 68, markerY: 26,
    isFavorite: false
  },
  {
    id: 5,
    title: '천연석 실버 목걸이 만들기',
    category: '주얼리',
    region: '성수동',
    studio: '아뜰리에 성수',
    schedule: '오늘 (화) 15:00 ~ 18:00',
    availableDays: ['월', '수', '금'],
    timeSlot: '오후',
    classFormat: '1:1 클래스',
    reservationOptions: ['당일 예약 가능'],
    transportType: '도보',
    transportTime: 9,
    distance: 700,
    price: 58000,
    popularity: 88,
    createdAt: '2026-06-14',
    image: 'images/sub1_3.png',
    lat: 37.5455, lng: 127.053,
    markerX: 40, markerY: 66,
    isFavorite: false
  },
  {
    id: 6,
    title: '탄생석 실버 팔찌 & 귀걸이',
    category: '주얼리',
    region: '강남',
    studio: '강남 주얼리랩',
    schedule: '모레 (목) 19:00 ~ 21:00',
    availableDays: ['화', '목', '토'],
    timeSlot: '저녁',
    classFormat: '소규모',
    reservationOptions: ['이번 주 예약 가능'],
    transportType: '차로',
    transportTime: 20,
    distance: 8200,
    price: 62000,
    popularity: 60,
    createdAt: '2026-06-05',
    image: 'images/sub1_3.png',
    lat: 37.4979, lng: 127.027,
    markerX: 86, markerY: 22,
    isFavorite: false
  },
  {
    id: 7,
    title: '칠보 물고기 키링 만들기',
    category: '금속공예',
    region: '성수동',
    studio: '성수 메탈공방',
    schedule: '오늘 (화) 16:00 ~ 18:30',
    availableDays: ['토', '일'],
    timeSlot: '오후',
    classFormat: '소규모',
    reservationOptions: ['당일 예약 가능'],
    transportType: '도보',
    transportTime: 11,
    distance: 880,
    price: 40000,
    popularity: 95,
    createdAt: '2026-06-16',
    image: 'images/sub1_4.png',
    lat: 37.5449, lng: 127.055,
    markerX: 58, markerY: 36,
    isFavorite: false
  },
  {
    id: 8,
    title: '커플 칠보 참장식 클래스',
    category: '금속공예',
    region: '건대입구',
    studio: '건대 크래프트',
    schedule: '주말 (토) 18:00 ~ 20:00',
    availableDays: ['토', '일'],
    timeSlot: '저녁',
    classFormat: '1:1 클래스',
    reservationOptions: [],
    transportType: '차로',
    transportTime: 12,
    distance: 2300,
    price: 48000,
    popularity: 65,
    createdAt: '2026-05-20',
    image: 'images/sub1_4.png',
    lat: 37.5402, lng: 127.069,
    markerX: 80, markerY: 58,
    isFavorite: false
  },
  {
    id: 9,
    title: '나만의 원목 볼펜 카빙',
    category: '우드공예',
    region: '성수동',
    studio: '우드워크 성수',
    schedule: '오늘 (화) 13:00 ~ 16:00',
    availableDays: ['목', '금', '토'],
    timeSlot: '오후',
    classFormat: '소규모',
    reservationOptions: ['당일 예약 가능'],
    transportType: '도보',
    transportTime: 5,
    distance: 400,
    price: 35000,
    popularity: 73,
    createdAt: '2026-06-13',
    image: 'images/sub1_5.png',
    lat: 37.5444, lng: 127.057,
    markerX: 36, markerY: 16,
    isFavorite: false
  },
  {
    id: 10,
    title: '원목 필기구 & 필통 만들기',
    category: '우드공예',
    region: '뚝섬',
    studio: '뚝섬 우드스튜디오',
    schedule: '내일 (수) 10:00 ~ 13:00',
    availableDays: ['수', '금'],
    timeSlot: '오전',
    classFormat: '단체 가능',
    reservationOptions: ['이번 주 예약 가능'],
    transportType: '차로',
    transportTime: 7,
    distance: 1600,
    price: 42000,
    popularity: 68,
    createdAt: '2026-06-11',
    image: 'images/sub1_5.png',
    lat: 37.5471, lng: 127.047,
    markerX: 22, markerY: 72,
    isFavorite: false
  },
  {
    id: 11,
    title: '제철 과일 화과자 클래스',
    category: '베이킹',
    region: '홍대',
    studio: '홍대 화과자랩',
    schedule: '주말 (일) 14:00 ~ 16:30',
    availableDays: ['토', '일'],
    timeSlot: '오후',
    classFormat: '소규모',
    reservationOptions: ['당일 예약 가능'],
    transportType: '차로',
    transportTime: 25,
    distance: 9500,
    price: 50000,
    popularity: 82,
    createdAt: '2026-06-09',
    image: 'images/sub1_1.png',
    lat: 37.5563, lng: 126.923,
    markerX: 16, markerY: 22,
    isFavorite: false
  },
  {
    id: 12,
    title: '데일리 실버 링 만들기',
    category: '주얼리',
    region: '잠실',
    studio: '잠실 실버스미스',
    schedule: '주말 (토) 18:00 ~ 20:00',
    availableDays: ['금', '토', '일'],
    timeSlot: '저녁',
    classFormat: '소규모',
    reservationOptions: [],
    transportType: '차로',
    transportTime: 30,
    distance: 12000,
    price: 45000,
    popularity: 72,
    createdAt: '2026-06-03',
    image: 'images/sub1_3.png',
    lat: 37.5133, lng: 127.100,
    markerX: 74, markerY: 80,
    isFavorite: false
  }
];

/* 정적 클러스터 마커(더미) — 실제 클러스터 계산 없이 표현용 */
const clusterMarkers = [
  { count: 3, x: 62, y: 30 },
  { count: 2, x: 28, y: 62 }
];

/* 필터 옵션 정의 */
const FILTER_OPTIONS = {
  regions: ['성수동', '서울숲', '건대입구', '뚝섬', '왕십리', '강남', '홍대', '잠실'],
  categories: ['베이킹', '주얼리', '금속공예', '우드공예'],
  days: ['월', '화', '수', '목', '금', '토', '일'],
  priceQuick: [
    { key: 'all', label: '전체', min: null, max: null },
    { key: 'u3', label: '3만원 이하', min: 0, max: 30000 },
    { key: 'b35', label: '3만원~5만원', min: 30000, max: 50000 },
    { key: 'b510', label: '5만원~10만원', min: 50000, max: 100000 },
    { key: 'o10', label: '10만원 이상', min: 100000, max: null }
  ],
  timeSlots: ['오전', '오후', '저녁'],
  classFormats: ['1:1 클래스', '소규모', '단체 가능'],
  reservationOptions: ['당일 예약 가능', '이번 주 예약 가능'],
  distances: [
    { key: '500', label: '500m 이내', m: 500 },
    { key: '1000', label: '1km 이내', m: 1000 },
    { key: '3000', label: '3km 이내', m: 3000 },
    { key: 'all', label: '거리 제한 없음', m: Infinity }
  ],
  sorts: [
    { key: 'distance', label: '가까운 순' },
    { key: 'popularity', label: '인기순' },
    { key: 'priceLow', label: '낮은 가격순' },
    { key: 'priceHigh', label: '높은 가격순' },
    { key: 'latest', label: '최신 등록순' }
  ],
  locations: ['성수동', '서울숲', '건대입구', '뚝섬', '왕십리', '강남', '홍대', '잠실']
};
